### ISSUE TITLE
或许可以支持短代码？

### ISSUE THREAD

**Issue by liuhao326** [zhuyuanxiang/pangu-markdown-vscode#3]
如：

同时使用`filename`参数来传入相对于 static 文件夹的文件路径。

添加空格变为：

同时使用 `filename` 参数来传入相对于 static 文件夹的文件路径

**Comment by zhuyuanxiang** [comment]
请问是哪里多出了空格？

**Comment by liuhao326** [comment]
短代码的两侧：
使用`filename`参数 => 使用 `filename` 参数

**Comment by zhuyuanxiang** [comment]
你是说在短代码的两边加上空格，是吗？

**Comment by zhuyuanxiang** [comment]
已经加入这个支持了，你试试看。

**Comment by liuhao326** [comment]
- 已生效，感谢！

- 我发现了一个问题：

  文本

  ```
  - 列表 1
  - 列表 2
  - 列表 3
    - 列表 4
  ```

  在使用命令之后会在符号 `-` 的后方添加两个空格，变成

  ```
  -   列表 1
  -   列表 2
  -   列表 3
    -   列表 4
  ```

- 另外希望能够支持右键，相比于命令行可能更方便。

**Comment by zhuyuanxiang** [comment]
1.  不客气
2.  加两个空格是我设置的格式决定的，因为 `-` 后面三个空格就可以与 `1.` 后面两个空格进行对齐，好像这种Markdown的格式是某一种标准推荐的，我也比较喜欢就采用了
3.  我没有提供缩进功能，因为缩进需要解析文档，类似于编译器的部分(这个我比较弱)就没做
    -   建议写Markdown可以使用 `VSCode+Typora`，一个进行可视化操作，一个提供源码编辑，非常方便
4.  右键功能(抱歉，暂时没时间做了)，建议你把格式化功能放在保存里面，这样子你保存文档的时候会自动格式化，可以在VSCode进行设置

**Comment by liuhao326** [comment]
哦， 好的。谢谢~
